version: "3"
services:
  php:
    image: project
    build:
      context: .
      dockerfile: Dockerfile
      networks:
        - studiomoto
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=4sfdg64s89g4sfd6g84sd6g45
      - MYSQL_DATABASE=stm
      - MYSQL_USER=stm
      - MYSQL_PASSWORD=stm
    networks:
      - studiomoto


networks:
  studiomoto:
    external: false
